import credentials from '../service/credentials/google_spreadsheets_api.js'
import { GoogleSpreadsheet } from 'google-spreadsheet'

export default async function getSheet(schema){
  const doc = new GoogleSpreadsheet('1Q8Lf_Eh38niPD04MrUYhsxMGBzpkpKHHD-awM3qEgJI');

  doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: credentials.client_email,
    private_key: credentials.private_key,
  });
  await doc.loadInfo();
  
  const sheet =  doc.sheetsByTitle[schema];
  return sheet;
}

// export default async function connectSpreadSheet(schema){

//     const doc = new GoogleSpreadsheet('1Q8Lf_Eh38niPD04MrUYhsxMGBzpkpKHHD-awM3qEgJI');

//     doc.useServiceAccountAuth({
//       // env var values are copied from service account credentials generated by google
//       // see "Authentication" section in docs for more info
//       client_email: credentials.client_email,
//       private_key: credentials.private_key,
//     });
//     await doc.loadInfo();
    
//     const sheet = doc.sheetsByTitle[schema];
//     const rows = await sheet.getRows(); 
    
//     let rowsUsers, rowsPosts,rowsTags,rowsCategories,rowsPages;
//     if(schema === 'posts') rowsPosts = rows.map((post) => (({
//       id:post.id,
//       content:post.content ? post.content : '<p>Ooops, algo deu errado, volte a página inicial</p>',
//       title:post.title ? post.title : '',
//       date:post.date ? post.date : '',
//       author:post.author ? post.author : '',
//       excerpt:post.excerpt ? post.excerpt : '',
//       thumbnail:post.thumbnail ? post.thumbnail : '',
//       tags:post.tags ? JSON.parse(post.tags) : [] ,
//       category:post.category ? post.category : '',
//       slug:post.slug ? post.slug : '',
//       is_public:post.is_public
//     })))
//     if(schema === 'pages') rowsPages = rows.map((page) => (({
//       id:page.id,
//       content:page.content ? page.content : '<p>Ooops, algo deu errado, volte a página inicial</p>',
//       title:page.title ? page.title : '',
//       date:page.date ? page.date : '',
//       author:page.author ? page.author : '',
//       excerpt:page.excerpt ? page.excerpt : '',
//       thumbnail:page.thumbnail ? page.thumbnail : '',
//       tags:page.tags ? JSON.parse(page.tags) : [] ,
//       category:page.category ? page.category : '',
//       slug:page.slug ? page.slug : '',
//       is_public:page.is_public
//     })))
//     if(schema === 'tags') rowsTags = rows.map(tag => ({
//       id:tag.id,
//       name:tag.name ? tag.name : '',
//       bg:tag.bg ? tag.bg : '',
//       color:tag.color ? tag.color : '',
//       icon:tag.icon ? tag.icon : '',
//     }))
//     if(schema === 'categories') rowsCategories = rows.map(category => ({
//       id:category.id,
//       name:category.name ? category.name : '',
//       bg:category.bg ? category.bg : '',
//       color:category.color ? category.color : '',
//       icon:category.icon ? category.icon : '',
//       excerpt:category.excerpt ? category.excerpt : '',
//       slug:category.slug ? category.slug : '',
//     }))
//     if(schema === 'users') rowsUsers = rows.map(({ accessToken, displayName, email, emailVerified, phoneNumber, photoURL, id, permission,password }) => ({ accessToken, displayName, email, emailVerified, phoneNumber, photoURL, id, permission,password }))
//     const nextRowId = rows.length + 1
//     return { doc , sheet, rows, nextRowId,rowsUsers,rowsPosts,rowsCategories,rowsTags,rowsPages}
// }